### PR TITLE
Refactor + add Docs

### LINKED ISSUE #1: Use `Oceananigans` pressure solver to compute the streamfunction
Oceananigans has a few solvers for the Poisson equation: `FFTBasedPoissonSolver`, `FourierTridiagonalPressureSolver`. You can use them this way

```julia
using Oceananigans.Solvers: FFTBasedPressureSolver
# ζ computed elsewhere, probably has to be `CenterField`.
ψ = CenterField(grid)
solver = FFTBasedPressureSolver(grid)
solve!(ψ, solver, ζ)
```

That's fewer lines than using FourierFlows and generalizes to any topology.

Probably, we want to interpolate `ψ` to cell corners before computing velocity:

```julia
ψffc = @at (Face, Face, Center) identity(ψ)
u .= - ∂y(ψffc)
v .= + ∂x(ψffc)
```

### PR DESCRIPTION
**Pull request by navidcy**
There are some leftover things to do after the refactor.

@glwagner, how do we change architecture? I presume we should make it so that the kwarg is provided to `word_to_simulation`, right?

Closes #1

### CODE REVIEW

**Comment by glwagner** [comment]
I think it's supported now, see:

https://github.com/navidcy/TurbulentWords.jl/blob/fb1ae95626de1f667c9e240e164bfad93251f837/src/simulations.jl#L3-L5

https://github.com/navidcy/TurbulentWords.jl/blob/fb1ae95626de1f667c9e240e164bfad93251f837/src/simulations.jl#L10-L12

**Comment by glwagner** [comment]
so the `other_kw` are propagated through

**Comment by navidcy** [comment]
This

https://github.com/navidcy/TurbulentWords.jl/blob/eecc82dc77eb600cdc09674e9aaaf7401b47313f/examples/hello_flow.jl#L13

takes quite a bit. How long should it take?

**Comment by glwagner** [comment]
> This
> 
> https://github.com/navidcy/TurbulentWords.jl/blob/eecc82dc77eb600cdc09674e9aaaf7401b47313f/examples/hello_flow.jl#L13
> 
> takes quite a bit. How long should it take?

it shouldn't take long at low resolution. I guess during a simulation you'd do one of those per time-step. it does one fft and one ifft.

**Comment by glwagner** [comment]
I guess it also does a few abstract operation computations which is maybe adding cost

**Comment by navidcy** [comment]
Oh ok. I was just wondering if the solver wasn't converging..

**Comment by glwagner** [comment]
> Oh ok. I was just wondering if the solver wasn't converging..

It's based on FFT, so no convergence

**Comment by navidcy** [comment]
Running the `hello_turbulence.jl` gives this:

https://github.com/navidcy/TurbulentWords.jl/assets/7112768/a68af195-9b02-4d4e-89d5-560a87c9bbe5

What's happening at the boundaries?

**Review by glwagner — APPROVED** [review]

**Pull request merged**
